; casjaysdevdocker/ampache - PHP-FPM 8.4 global config

[global]
pid = /run/php-fpm/php-fpm.pid
error_log = /data/logs/php-fpm/error.log
log_level = notice
emergency_restart_threshold = 0
emergency_restart_interval = 0
process_control_timeout = 0
daemonize = no

include = /etc/php84/php-fpm.d/*.conf
